development:
  adapter: postgresql
  encoding: unicode
  database: wedding_app_development
  pool: 5
  username: rigelstpierre
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: wedding_app_test
  pool: 5
  username: rigelstpierre 
  password:

